AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

require:
  - rubocop-rspec
  - rubocop-rake

Layout/LineLength:
  Max: 180

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Enabled: false

Metrics/MethodLength:
  Max: 11

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
