#!/usr/bin/env ruby

# frozen_string_literal: true

require 'json'
require "random_name_generator"
require "slop"

lang = RandomNameGenerator::FANTASY

opts = Slop.parse do |o|
  o.bool "-e", "--elven", "Use Elven eyllable file"
  o.bool "-g", "--goblin", "Use Goblin eyllable file"
  o.bool "-r", "--roman", "Use Roman eyllable file"
  o.bool "-f", "--flipmode", "Flip mode in effect"
  o.bool "-c", "--cyrillic", "Use Cyrillic mode"
  o.bool "-j", "--json", "dumps out a language object as JSON"
  o.bool "-x", "--xrated", "Generate Curse words [NEEDS WORK]"
  o.bool "-?", "--help", "How to"
end

if opts.cyrillic?
  lang = RandomNameGenerator::FANTASY_RU
  lang = RandomNameGenerator::ELVEN_RU if opts.elven?
  lang = RandomNameGenerator::GOBLIN_RU if opts.goblin?
  lang = RandomNameGenerator::ROMAN_RU if opts.roman?
else
  lang = RandomNameGenerator::ELVEN if opts.elven?
  lang = RandomNameGenerator::GOBLIN if opts.goblin?
  lang = RandomNameGenerator::ROMAN if opts.roman?
  lang = RandomNameGenerator::CURSE if opts.xrated?
end

if opts.json?
  rndgen = RandomNameGenerator.new(lang)
  puts rndgen.syllables
elsif opts.flipmode?
  if opts.cyrillic?
    puts "#{RandomNameGenerator.flip_mode_cyrillic.compose} #{RandomNameGenerator.flip_mode_cyrillic.compose}"
  else
    puts "#{RandomNameGenerator.flip_mode.compose} #{RandomNameGenerator.flip_mode.compose}"
  end
elsif opts.help?
  puts opts
else
  rndgen = RandomNameGenerator.new(lang)
  puts "#{rndgen.compose} #{rndgen.compose}"
end
